Nginx経由で画像を表示できるようにする
kakke18/isucon7-qualify pull request #18
Opened 2020-07-16 20:56 UTC by kakke18

preTestで「画像が正しく表示できません」と言われて死ぬ

2020-07-24 05:20 UTC, yuuis requested changes
画像はignoreしてほしー！

2020-07-24 08:36 UTC, kakke18 commented on conf/nginx/sites-enabled/nginx.conf
> +
GCE上で開くとインデントはずれていなので大丈夫

2020-07-24 08:36 UTC, kakke18 commented on bench/vendor/manifest
> -{
何で消えたかわからんけどまあ大丈夫でしょ

2020-07-24 11:58 UTC, yuuis approved these changes
![unun](https://user-images.githubusercontent.com/31527437/88388816-339d1880-cdf0-11ea-90de-68bfcbff46a6.gif)

2020-08-05 11:07 UTC, gal1996 approved these changes

2020-08-05 11:08 UTC, merged